app_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: /index.html.twig
    methods: GET


cloud-controllers:
    resource: '../src/Controller/Cloud'
    type: annotation

cloud-api-controllers:
    resource: '../src/Controller/Cloud/API'
    type: annotation
    prefix: '/api/cloud'
