#index:
#    path: /
#    controller: App\Controller\DefaultController::index

cloud-controllers:
    resource: '../src/Controller'
    type: annotation

cloud-api-controllers:
    resource: '../src/Controller/API'
    type: annotation
    prefix: '/api/cloud'